#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path("public/agent_crypto_erith_ia/administrator")
INDEX = (ROOT / "index.html").read_text(encoding="utf-8")
JS_PATH = ROOT / "js/market-microscope-candles.js"
PAIR_PATH = ROOT / "js/okx-market-pair-resolver.js"
APP_PATH = ROOT / "app.js"
JS = JS_PATH.read_text(encoding="utf-8")
PAIR = PAIR_PATH.read_text(encoding="utf-8")
APP = APP_PATH.read_text(encoding="utf-8")
BUILD = json.loads((ROOT / "build.json").read_text(encoding="utf-8"))

def need(ok, msg):
    if not ok:
        raise SystemExit("MARKET_MICROSCOPE_GUARD_FAIL: " + msg)

CURRENT = str(BUILD.get("build") or "").strip()
PARENT = str(BUILD.get("parent_build") or "").strip()
need(bool(CURRENT), "current build")
need(bool(PARENT), "parent build")
need(BUILD.get("market_core") == "38.15.11", "Market Core")
need(f"market-microscope-candles.js?v={CURRENT}" in INDEX, "canonical runtime cache token")
need("market-microscope-candles-406498.js" not in INDEX, "legacy runtime referenced by current index")
need(not (ROOT / "js/market-microscope-candles-406498.js").exists(), "legacy runtime file still active")
need('const BUILD="' in JS, "module build metadata")
need('const HISTORICAL_CORE_BUILD="40.6.498"' in JS, "historical lineage metadata")
need('const INDICATOR_STORAGE_KEY="agentCrypto.marketMicroscope.indicators.v1"' in JS, "stable indicator state owner")
need("indicators:readIndicatorState()" in JS, "indicator state restore")
need("persistIndicatorState();" in JS, "indicator state persist")
need("localStorage?.setItem(INDICATOR_STORAGE_KEY" in JS, "localStorage persistence")
need("sessionStorage?.setItem(INDICATOR_STORAGE_KEY" in JS, "sessionStorage fallback")
need("atlasCandlesTechnicalLevels406551" not in JS, "versioned DOM id remains")
need("__agentCryptoMicroscope561" not in JS and "__agentCryptoMicroscope562" not in JS, "versioned hook marker remains")
need("__agentCryptoMicroscopeHook" not in JS and "__agentCryptoMicroscopeOriginal" not in JS, "legacy global selection wrapper remains")
need('window.dispatchEvent(new CustomEvent("agent-crypto:selected-market-changed"' in APP, "canonical selection event owner missing")
need('window.addEventListener("agent-crypto:selected-market-changed",handleCanonicalSelectionChanged' in JS, "Candles canonical selection listener missing")
need("canonical_market_selection_event:true" in JS, "Candles event contract missing")
need("stale_asset_canvas_cleared:true" in JS, "stale asset canvas truth missing")
need('if(!state.rows.length&&!state.loadedInstrument)state.instrument=primary;' in JS, "requested instrument not projected before first successful load")
need("movingAverage(state.rows,n).slice(view.start,view.start+rows.length)" in JS, "MA full-history projection")
need("exponentialAverage(state.rows,n).slice(view.start,view.start+rows.length)" in JS, "EMA full-history projection")
need('method:"PIVOTS_VISIBLES_W2"' in JS, "S/R method")
need("latest_request_wins:true" in JS, "latest request wins")
need("request_timeout_ms:REQUEST_TIMEOUT_MS" in JS, "request timeout")
need("indicator_state_roundtrip:indicatorRoundTrip" in JS, "indicator roundtrip self-test")
need("strict_null_ohlc_rejected:nullOhlcRejected" in JS, "null OHLC validation")
need("strict_incoherent_ohlc_rejected:incoherentOhlcRejected" in JS, "OHLC coherence validation")
need("empty_parsed_series_rejected:emptySeriesRejected" in JS, "empty parsed series validation")
need("timeout_has_explicit_error:timeoutTruth" in JS, "timeout truth self-test")
need("OKX_LOCAL_TIMEOUT" in JS, "explicit local timeout error")
need("OKX_LOCAL_UNAVAILABLE" in JS, "explicit local backend unavailable error")
fetch_start = JS.find("async function fetchInstrument")
http_status = JS.find("if(!r.ok)", fetch_start)
json_parse = JS.find("await r.json()", fetch_start)
need(fetch_start >= 0 and http_status > fetch_start and json_parse > http_status, "HTTP status must be classified before JSON parsing")
need("http_status_checked_before_json:true" in JS, "HTTP-before-JSON runtime contract missing")
need("pair_http_400_fallback:pairHttp400Fallback" in JS, "HTTP 400 fallback self-test missing")
need("response_invalid_no_pair_fallback:responseInvalidNoPairFallback" in JS, "invalid-response fallback guard missing")
need("canTryNextPair(error)" in JS, "bounded next-pair fallback")
need(f"okx-market-pair-resolver.js?v={CURRENT}" in INDEX, "shared pair resolver cache token")
need(INDEX.find("js/okx-market-pair-resolver.js") < INDEX.find("js/market-microscope-candles.js"), "pair resolver must load before Candles")
need("AgentCryptoOkxMarketPairResolver" in JS, "Candles do not consume shared pair resolver")
need("const instrumentCandidates=" in JS, "shared candidate projection missing")
need('["USDC","USDT"]' in PAIR, "USD pair order missing")
need('status===400||status===404' in PAIR, "bounded HTTP pair fallback missing")
need('network:"OKX_PUBLIC_VIA_LOCAL_BACKEND_ON_DEMAND_OR_NEW_LISTING_PROVIDER"' in JS, "network truth")
need('storage_scope:"INDICATOR_STATE_PLUS_INTERVAL_PREFERENCE"' in JS, "bounded storage scope")
need('const BAR_STORAGE_KEY="agentCrypto.marketMicroscope.bar.v1"' in JS, "stable interval preference owner")
need("readBarPreference()" in JS, "interval preference restore")
need("persistBarPreference(state.bar);" in JS, "operator interval preference persist")
need("bar_preference_storage_key:BAR_STORAGE_KEY" in JS, "interval preference self-test")
need('class="amm-intervals"><div class="amm-bar">' in JS, "interval buttons retained without label")
need('<small>INTERVALLE</small>' not in JS, "INTERVALLE label removed")
need("responsive_single_line_toolbar:true" in JS, "responsive single-line toolbar export")
need("interval_label_removed:true" in JS, "interval label removal export")
need("narrow_wrap_two_rows:true" in JS, "narrow two-row fallback export")
need("canvas_vertical_reclaim:true" in JS, "canvas reclaim export")
need('classList.toggle("is-two-row-controls",twoRows)' in JS, "DOM geometry row detector")
need("#${ROOT}.is-two-row-controls .amm-tip{top:72px}" in JS, "two-row inspector fallback")
need("#${ROOT} .amm-tip{position:absolute;z-index:4;display:block;left:12px;right:12px;top:39px;" in JS, "single-row inspector reclaim")
need("else if(c.parentElement!==host)host.appendChild(c);" in JS, "controls idempotent reparent")
need("if(root.parentElement!==sh)sh.appendChild(root);" in JS, "chart root idempotent reparent")
need("function scheduleLayoutRefresh()" in JS, "bounded view layout refresh")
need('window.addEventListener("atlas:v2mode",scheduleLayoutRefresh' in JS, "v2 mode layout refresh")
need('window.addEventListener("atlas:admin-graph",scheduleLayoutRefresh' in JS, "admin graph layout refresh")
need("view_layout_refresh_no_fetch:true" in JS, "layout refresh no-fetch contract")
need("stable_control_rows:true" in JS, "stable control row export")
need("compact_meta:true" in JS, "compact meta export")
need("verbose_indicator_meta_removed:true" in JS, "verbose meta removal export")
need("O/H/L/C + Volume · ${indicators}" not in JS, "verbose indicator inventory still rendered in header")
need("${shownInstrument} · ${shownBar} · ${state.rows.length} bougies · ${metaProvider}" in JS, "compact runtime metadata contract")
need("real_order:false" in JS, "no real orders")
need("recurring_timer:false" in JS, "no recurring timer")

scope = BUILD.get("market_microscope_runtime") or {}
need(scope.get("owner") == "js/market-microscope-candles.js", "manifest canonical owner")
need(scope.get("transport_owner") == "js/okx-local-backend-transport.js", "manifest transport owner")
need(scope.get("transport_runtime") == "LOCAL_BACKEND_127.0.0.1_8790", "manifest local backend truth")
need(scope.get("direct_browser_okx_fetch") is False, "direct browser OKX disabled")
need(scope.get("timeout_silent_fixed") is True, "timeout repair manifest")
need(scope.get("strict_ohlc_validation") is True, "strict OHLC manifest")
need(scope.get("empty_parsed_series_rejected") is True, "empty series manifest")
need(scope.get("eur_fallback_on_transport_failure") is False, "transport failure fallback guard")
need(scope.get("stable_control_rows") is True, "manifest stable control rows")
need(scope.get("responsive_single_line_toolbar") is True, "manifest responsive single-line toolbar")
need(scope.get("interval_label_removed") is True, "manifest interval label removed")
need("interval_label" not in scope, "stale INTERVALLE manifest field removed")
need(scope.get("toolbar_single_line_preferred") is True, "manifest desktop single-line preference")
need(scope.get("narrow_wrap_two_rows") is True, "manifest narrow two-row fallback")
need(scope.get("control_row_wrapping") is True, "manifest responsive control wrapping")
need(scope.get("canvas_vertical_reclaim") is True, "manifest canvas reclaim")
need(scope.get("layout_only_no_fetch") is True, "manifest layout-only no-fetch")
need(scope.get("idempotent_mount_reparent") is True, "manifest idempotent mount")
need(scope.get("view_layout_refresh_no_fetch") is True, "manifest layout refresh no fetch")
need(scope.get("mode_persistence_added") is False, "no hidden mode persistence")
need(scope.get("interval_persistence_added") is True, "interval persistence manifest")
need(scope.get("interval_storage_owner") == "agentCrypto.marketMicroscope.bar.v1", "interval storage owner")
need(scope.get("interval_operator_choice_persisted") is True, "operator interval persistence")
need(scope.get("interval_programmatic_load_overwrites_preference") is False, "programmatic load does not overwrite interval preference")
need(scope.get("compact_meta") is True, "manifest compact meta")
need(scope.get("verbose_indicator_meta_removed") is True, "manifest verbose meta removed")
need(scope.get("meta_no_indicator_duplication") is True, "manifest no indicator duplication")
need(scope.get("meta_single_line") is True, "manifest single-line meta")
need(scope.get("storage_changed") is True, "manifest storage changed only for interval preference")
need(scope.get("storage_additive_only") is True, "manifest additive storage")
need(scope.get("storage_deletion") is False, "manifest no storage deletion")
need(scope.get("formulas_changed") is False, "formulas unchanged")
need(scope.get("market_core_modified") is False, "Market Core unchanged")
need(scope.get("no_storage_deletion") is True, "storage non-destructive")

print(json.dumps({
    "ok": True,
    "build": CURRENT,
    "parent": PARENT,
    "runtime": "js/market-microscope-candles.js",
    "module_build_is_lineage_metadata": True,
    "transport": scope.get("transport_runtime"),
    "indicator_state_owner": scope.get("indicator_state_owner"),
    "market_core": BUILD.get("market_core"),
    "terrain": BUILD.get("terrain_proof")
}))
